# Generated by Django 6.0.6 on 2026-07-18 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_product', models.JSONField(blank=True, default=list)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('rag_context', models.JSONField(blank=True, default=dict)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'AI Assistant')], default='user', max_length=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='shop.product')),
            ],
        ),
    ]
