# Generated by Django 6.0.6 on 2026-07-18 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=10)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='master_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shop_master_name_4488a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('sub_Category', models.CharField(default='', max_length=100)),
                ('article_Type', models.CharField(default='', max_length=50)),
                ('colour', models.CharField(default='', max_length=50)),
                ('gender', models.TextField(default='Not Specified', max_length=50)),
                ('season', models.CharField(default='', max_length=50)),
                ('usage', models.CharField(default='', max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='shop/images/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('master_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.master_category')),
            ],
            options={
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'), models.Index(fields=['product_name'], name='shop_produc_product_8ef27c_idx'), models.Index(fields=['-created_date'], name='shop_produc_created_01bbf8_idx')],
            },
        ),
    ]
